//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIUSPTToDDL.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIUSPTToDDL.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Invoice xmlns:cbc=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2&quot; xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot;&gt;
        ///  &lt;cbc:UBLVersionID&gt;2.1&lt;/cbc:UBLVersionID&gt;
        ///  &lt;cbc:CustomizationID&gt;urn:cen.eu:en16931:2017#compliant#urn:feap.gov.pt:CIUS-PT:1.0.0.&lt;/cbc:CustomizationID&gt;
        ///  &lt;cbc:ID&gt;FAC 1/686&lt;/cb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ciusptSampleFile {
            get {
                return ResourceManager.GetString("ciusptSampleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Invoice xmlns:cbc=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2&quot; xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot;&gt;
        ///  &lt;cbc:UBLVersionID&gt;2.1&lt;/cbc:UBLVersionID&gt;
        ///  &lt;cbc:CustomizationID&gt;urn:cen.eu:en16931:2017#compliant#urn:feap.gov.pt:CIUS-PT:1.0.0.&lt;/cbc:CustomizationID&gt;
        ///  &lt;cbc:ID&gt;FAC 1/710&lt;/cb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ciusptSampleFile2 {
            get {
                return ResourceManager.GetString("ciusptSampleFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Invoice
        ///	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2 ../oasis/maindoc/UBL-Invoice-2.1.xsd&quot;
        ///	xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot;
        ///	xmlns:cbc=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2&quot;
        ///	xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2&quot;&gt;
        ///	&lt;cbc:CustomizationID&gt;urn:cen.eu:en16931:2017#compliant#u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ciusptSampleFile3 {
            get {
                return ResourceManager.GetString("ciusptSampleFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;CreditNote
        ///	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2 ../oasis/maindoc/UBL-CreditNote-2.1.xsd&quot;
        ///	xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2&quot;
        ///	xmlns:cbc=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2&quot;
        ///	xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2&quot;&gt;
        ///	&lt;cbc:CustomizationID&gt;urn:cen.eu:en16931:2017 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ciusptSampleFile4 {
            get {
                return ResourceManager.GetString("ciusptSampleFile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Invoice
        ///	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2 ../oasis/maindoc/UBL-Invoice-2.1.xsd&quot;
        ///	xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot;
        ///	xmlns:cbc=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2&quot;
        ///	xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2&quot;&gt;
        ///	&lt;cbc:CustomizationID&gt;urn:cen.eu:en16931:2017#compliant#u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ciusptSampleFile5 {
            get {
                return ResourceManager.GetString("ciusptSampleFile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Invoice
        ///	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2 ../oasis/maindoc/UBL-Invoice-2.1.xsd&quot;
        ///	xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot;
        ///	xmlns:cbc=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2&quot;
        ///	xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2&quot;&gt;
        ///	&lt;cbc:CustomizationID&gt;urn:cen.eu:en16931:2017#compliant#u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ciusptSampleFile6 {
            get {
                return ResourceManager.GetString("ciusptSampleFile6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Invoice xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2&quot; xmlns:cbc=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2&quot; xmlns:ext=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2&quot; xmlns:n2=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2&quot; xmlns:qdt=&quot;urn:oasis:names:specification:ubl:schema:xsd:QualifiedDataTypes-2&quot; xmlns:sac=&quot;urn:oasis:names:specification:ubl:schem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ciusptSampleFile7 {
            get {
                return ResourceManager.GetString("ciusptSampleFile7", resourceCulture);
            }
        }
    }
}
